## Concentra mas Numpy

In [ ]:
import numpy as np
import random

Criando um vetor com os seguintes valores [1,2,3,4,5], chame-o de vetA

In [ ]:
vetA = np.array([1,2,3,4,5])

Exiba os 3 primeiros elementos

In [ ]:
vetA[:3]

array([1, 2, 3])

Exiba todos os valores após o quinto elemento

In [ ]:
vetA[5:]

array([], dtype=int64)

Exiba os 3 últimos elementos

In [ ]:
vetA[-3:]

array([3, 4, 5])

Exiba os valores de vetA entre o 5 elemento até o penúltimo elemento:

In [ ]:
vetA[5:-2]

array([], dtype=int64)

Crie uma matriz 5x5

In [ ]:
matrizA = np.random.randint(1, 100, (5,5))

Exiba a matriz inteira

In [ ]:
matrizA

array([[84, 73, 66, 49, 73],
       [56, 86, 90, 25, 82],
       [43, 28, 50, 88, 85],
       [86, 75, 24, 73, 15],
       [85, 69, 98, 53, 85]])

Exiba todos os elementos da coluna 3

In [ ]:
matrizA[:,2]

array([66, 90, 50, 24, 98])

Exiba todos os elementos da linha 2

In [ ]:
matrizA[1,:]

array([56, 86, 90, 25, 82])

Exiba todos os elementos das 2 primeiras colunas

In [ ]:
matrizA[:,:2]

array([[84, 73],
       [56, 86],
       [43, 28],
       [86, 75],
       [85, 69]])

Exiba todos os elementos das 2 primeiras linhas



In [ ]:
matrizA[:2,:]

array([[84, 73, 66, 49, 73],
       [56, 86, 90, 25, 82]])

Exiba Apenas os elementos das 2 últimas linhas e das 4 últimas colunas

In [ ]:
matrizA[-2:,-4:]

array([[75, 24, 73, 15],
       [69, 98, 53, 85]])

Crie uma função que receba dois vetores e realize a soma de seus valores.

In [ ]:
def sum_vectors(vector1, vector2):
  return vector1 + vector2

Generalize a função acima para que ela receba uma string representando a operação a ser executada: '+' ou '-'

In [ ]:
def sum_vectors(vector1, vector2, operator):
  if operator == '+':
    return vector1 + vector2
  elif operator == '-':
    return vector1 - vector2
  else:
    return "Choose another operator."

Como calcular a média dos valores de uma matriz

In [ ]:
matrizA.mean()
# ou np.mean(matrizA)

65.64

Calcule apenas a média das linhas

In [ ]:
matrizA.mean(1)
# ou np.mean(matrizA, axis=1)

array([69. , 67.8, 58.8, 54.6, 78. ])

Calcule apenas a média das colunas

In [ ]:
matrizA.mean(0)
# ou np.mean(matrizA, axis=2)

array([70.8, 66.2, 65.6, 57.6, 68. ])

## O PY tá on

Crie uma lista de 3 elementos e calcule a terceira potência de cada elemento

In [ ]:
list1 = [7, 5, 9]
for number in list1:
  print(number ** 3)

343
125
729


Crie uma função que receba uma frase e, para cada palavra, retorne uma lista contendo a palavra original, sua versão
minúscula e a quantidade de caracteres.
* Ex: 'Eu AMO Carnaval' deverá retornar:

['Eu', 'eu', 2]

['AMO', 'amo', 3]

['Carnaval', 'carnaval', 8]

In [ ]:
def analyze_word(sentence):
  list_of_words = sentence.split()
  result_list = []
  for word in list_of_words:
    words_analyzed = []
    words_analyzed.append(word)
    words_analyzed.append(word.lower())
    words_analyzed.append(len(word))
    result_list.append(words_analyzed)
  return result_list

In [ ]:
print(analyze_word("Eu AMO Carnaval"))

[['Eu', 'eu', 2], ['AMO', 'amo', 3], ['Carnaval', 'carnaval', 8]]


Abaixo você encontra duas listas. Faça com que cada elemento da listaA seja elevado ao elemento correspondente na listaB.

listaA = [2, 3, 4]

listaB = [10, 11, 12]

In [ ]:
listaA = [2,3,4]
listaB = [10,11,12]
for number1 in listaA:
  for number2 in listaB:
    print(number1 ** number2)

1024
2048
4096
59049
177147
531441
1048576
4194304
16777216


Considere os dois dicionários abaixo. Crie um terceiro dicionário com as chaves do dicionário 1 e os valores do dicionário 2.

dict1 = {'a':1,'b':2}

dict2 = {'c':4,'d':5}

In [ ]:
dict1 = {"a": 1, "b": 2}
dict2 = {"c": 4, "b": 5}

def build_dict():
  dict3 = {}
  for index, key in enumerate(dict1):
      dict3[key] = list(dict2.values())[index]
  return dict3
      
build_dict()

{'a': 4, 'b': 5}

## Tem Pandas na Folia

Utilizando o arquivo bikes.csv, utilize todos os seus conhecimentos de pandas para retornar informações sobre esse dataset.

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = '/content/drive/MyDrive/Bootcamp_Data_Science/DBs/bikes.csv'

In [ ]:
bikes_df = pd.read_csv(path)

In [ ]:
bikes_df

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
...                    ...     ...      ...         ...      ...    ...   
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14.76   
10883  2012-12-19 21:00:00       4        0           1        1  13.94   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10886 rows x 12 columns]

In [ ]:
bikes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   datetime    10886 non-null  object 
 1   season      10886 non-null  int64  
 2   holiday     10886 non-null  int64  
 3   workingday  10886 non-null  int64  
 4   weather     10886 non-null  int64  
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64  
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64  
 10  registered  10886 non-null  int64  
 11  count       10886 non-null  int64  
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


Existem valores nulos?

In [ ]:
bikes_df.isnull()

datetime  season  holiday  workingday  weather   temp  atemp  humidity  \
0         False   False    False       False    False  False  False     False   
1         False   False    False       False    False  False  False     False   
2         False   False    False       False    False  False  False     False   
3         False   False    False       False    False  False  False     False   
4         False   False    False       False    False  False  False     False   
...         ...     ...      ...         ...      ...    ...    ...       ...   
10881     False   False    False       False    False  False  False     False   
10882     False   False    False       False    False  False  False     False   
10883     False   False    False       False    False  False  False     False   
10884     False   False    False       False    False  False  False     False   
10885     False   False    False       False    False  False  False     False   

       windspeed  casual  registered  count  
0          False   False       False  False  
1          False   False       False  False  
2          False   False       False  False  
3          False   False       False  False  
4          False   False       False  False  
...          ...     ...         ...    ...  
10881      False   False       False  False  
10882      False   False       False  False  
10883      False   False       False  False  
10884      False   False       False  False  
10885      False   False       False  False  

[10886 rows x 12 columns]

In [ ]:
bikes_df[bikes_df.isna().any(axis=1)]

Empty DataFrame
Columns: [datetime, season, holiday, workingday, weather, temp, atemp, humidity, windspeed, casual, registered, count]
Index: []

Exiba uma Series

In [ ]:
bikes_df["humidity"]

0        81
1        80
2        80
3        75
4        75
         ..
10881    50
10882    57
10883    61
10884    61
10885    66
Name: humidity, Length: 10886, dtype: int64

Exiba uma seleção de 3 colunas

In [ ]:
bikes_df[["datetime", "season", "temp"]]

datetime  season   temp
0      2011-01-01 00:00:00       1   9.84
1      2011-01-01 01:00:00       1   9.02
2      2011-01-01 02:00:00       1   9.02
3      2011-01-01 03:00:00       1   9.84
4      2011-01-01 04:00:00       1   9.84
...                    ...     ...    ...
10881  2012-12-19 19:00:00       4  15.58
10882  2012-12-19 20:00:00       4  14.76
10883  2012-12-19 21:00:00       4  13.94
10884  2012-12-19 22:00:00       4  13.94
10885  2012-12-19 23:00:00       4  13.12

[10886 rows x 3 columns]

Crie uma função lambda que converta a temperatura de Celsius para Fahrenheit

In [ ]:
temp_farenheit = lambda temp: temp * 1.8 + 32

Em season temos os valores 1, 2, 3 e 4 que representam as categorias:

1 = spring

2 = summer

3 = fall

4 = winter

Utilizando o map, altere os valores numéricos para suas respectivas categorias

In [ ]:
seasons = {1: "spring", 2: "summer", 3: "fall", 4: "winter"}

bikes_df['season'] = bikes_df['season'].map(seasons)


Demonstre a utilização do LOC

In [ ]:
bikes_df.loc[[10, 13]]

datetime  season  holiday  workingday  weather   temp   atemp  \
10  2011-01-01 10:00:00  spring        0           0        1  15.58  19.695   
13  2011-01-01 13:00:00  spring        0           0        2  18.86  22.725   

    humidity  windspeed  casual  registered  count  
10        76    16.9979      12          24     36  
13        72    19.9995      47          47     94

Demonstre a utilização do iLOC

In [ ]:
bikes_df.iloc[10:14, :]

datetime  season  holiday  workingday  weather   temp   atemp  \
10  2011-01-01 10:00:00  spring        0           0        1  15.58  19.695   
11  2011-01-01 11:00:00  spring        0           0        1  14.76  16.665   
12  2011-01-01 12:00:00  spring        0           0        1  17.22  21.210   
13  2011-01-01 13:00:00  spring        0           0        2  18.86  22.725   

    humidity  windspeed  casual  registered  count  
10        76    16.9979      12          24     36  
11        81    19.0012      26          30     56  
12        77    19.0012      29          55     84  
13        72    19.9995      47          47     94

Explique a diferença entre eles:

Utiliza-se loc para retornar linhas através de labels. No caso do uso do loc acima, o 10 e o 13 representam os labels do índice e não ao índice em si. Para acessar utilizando o índice, é necessário o uso do iloc. Através do iloc também é possível realizar slices, retornando uma faixa de linhas a serem consultadas.

Crie um filtro de sua preferência, armazene-o em uma variável e apresente sua aplicação

In [ ]:
bikes_df[(bikes_df["humidity"] < 50) & (bikes_df["season"] == "winter")]

datetime  season  holiday  workingday  weather   temp  \
4162   2011-10-05 11:00:00  winter        0           1        1  24.60   
4163   2011-10-05 12:00:00  winter        0           1        1  25.42   
4164   2011-10-05 13:00:00  winter        0           1        1  26.24   
4165   2011-10-05 14:00:00  winter        0           1        1  26.24   
4166   2011-10-05 15:00:00  winter        0           1        1  26.24   
...                    ...     ...      ...         ...      ...    ...   
10855  2012-12-18 17:00:00  winter        0           1        1  16.40   
10856  2012-12-18 18:00:00  winter        0           1        1  15.58   
10857  2012-12-18 19:00:00  winter        0           1        1  15.58   
10860  2012-12-18 22:00:00  winter        0           1        1  13.94   
10861  2012-12-18 23:00:00  winter        0           1        1  13.94   

        atemp  humidity  windspeed  casual  registered  count  
4162   31.060        46    19.0012      32         138    170  
4163   31.060        43    22.0028      34         180    214  
4164   31.060        41    15.0013      30         189    219  
4165   31.060        41    19.0012      34         156    190  
4166   31.060        47    19.0012      35         147    182  
...       ...       ...        ...     ...         ...    ...  
10855  20.455        47    30.0026      39         533    572  
10856  19.695        46    22.0028      13         512    525  
10857  19.695        46    26.0027      19         334    353  
10860  16.665        49     0.0000       5         127    132  
10861  17.425        49     6.0032       1          80     81  

[584 rows x 12 columns]

Revise nossas aulas de Pandas. Você conseguiria utilizar alguma das funções aprendidas neste conjunto de dados para
obter insights para o negócio?

## Bloco de Dados

In [ ]:
import sqlite3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/Bootcamp_Data_Science/DBs/restaurant_sqlite.db'
conn = sqlite3.connect(path)

In [ ]:
def execute_query(query):
  return pd.read_sql(query, conn)

In [ ]:
execute_query("SELECT * FROM sqlite_master WHERE type = 'table'")

type             name         tbl_name  rootpage  \
0  table     Reservations     Reservations         2   
1  table     OrdersDishes     OrdersDishes         3   
2  table           Orders           Orders         4   
3  table  EventsLocations  EventsLocations         5   
4  table           Events           Events         6   
5  table           Dishes           Dishes         7   
6  table  CustomersEvents  CustomersEvents         8   
7  table  CustomersDishes  CustomersDishes         9   
8  table        Customers        Customers        10   

                                                 sql  
0  CREATE TABLE "Reservations" (\n\t"ReservationI...  
1  CREATE TABLE "OrdersDishes" (\n\t"OrdersDishes...  
2  CREATE TABLE "Orders" (\n\t"OrderID"\tINTEGER,...  
3  CREATE TABLE "EventsLocations" (\n\t"id"\tINTE...  
4  CREATE TABLE "Events" (\n\t"EventID"\tINTEGER,...  
5  CREATE TABLE "Dishes" (\n\t"DishID"\tINTEGER,\...  
6  CREATE TABLE "CustomersEvents" (\n\t"Customers...  
7  CREATE TABLE "CustomersDishes" (\n\t"Customers...  
8  CREATE TABLE "Customers" (\n\t"CustomerID"\tIN...

Exibir os pratos mais baratos.

In [ ]:
execute_query("""
SELECT * FROM Dishes
ORDER BY Price
LIMIT 10""")

DishID                     Name  \
0      21     Pomegranate Iced Tea   
1      18                Apple Pie   
2      17   Chocolate Chip Brownie   
3      20   Tropical Blue Smoothie   
4      22               Cafe Latte   
5       3        French Onion Soup   
6       5  Panko Stuffed Mushrooms   
7       7              House Salad   
8      19         Mixed Berry Tart   
9       1    Parmesan Deviled Eggs   

                                         Description  Price  
0  Our unique blend of pomegranate juice, black R...    4.0  
1  Made with local granny smith apples to bring y...    5.0  
2  A warm chocolate chip brownie served with choc...    6.0  
3  This blueberry mint-based smoothie is refreshi...    6.0  
4  Our house blend of espresso and foamed milk. C...    6.0  
5  Caramelized onions slow cooked in a savory bro...    7.0  
6  Large mushroom caps are filled a savory cream ...    7.0  
7  Our house salad is made with romaine lettuce a...    7.0  
8  Raspberries, blueberries, and strawberries on ...    7.0  
9  These delectable little bites are made with or...    8.0

Exibir os clientes mais frequentes.

In [ ]:
execute_query("""
SELECT CustomerID, COUNT(*) AS count FROM Orders
GROUP BY CustomerID
ORDER BY count DESC
""")

CustomerID  count
0          17      3
1           2      1
2          39      1
3          45      1
4          51      1
5          66      1
6          71      1
7          86      1

Quais clientes gastam mais?

In [ ]:
execute_query("""
SELECT o.CustomerID, c.FirstName, c.LastName, SUM(d.Price) AS total FROM Orders o
INNER JOIN OrdersDishes od ON o.OrderID = od.Orderid
INNER JOIN Dishes d ON d.Dishid = od.Dishid
INNER JOIN Customers c ON c.CustomerID = o.CustomerID
GROUP BY o.CustomerID
ORDER BY total DESC
LIMIT 5
""")

CustomerID FirstName  LastName  total
0          17      Lani      Over  35.98
1          71    Winnah    D'Elia  26.98
2           2    Javier     Dawks  25.99
3          66   Gilbert     Dupoy  23.98
4          86  Brandais  Jeannaud  16.99

O que esses clientes que gastam mais, costumam pedir?

In [ ]:
execute_query("""
SELECT d.name, COUNT(*) AS frequency FROM dishes d
INNER JOIN ordersdishes od ON d.dishid = od.dishid
INNER JOIN orders o ON o.orderid = od.orderid
INNER JOIN customers c ON c.customerid = o.customerid
WHERE o.customerid IN (SELECT o.CustomerID FROM Orders o
INNER JOIN OrdersDishes od ON o.OrderID = od.Orderid
INNER JOIN Dishes d ON d.Dishid = od.Dishid
INNER JOIN Customers c ON c.CustomerID = o.CustomerID
GROUP BY o.CustomerID
ORDER BY SUM(d.price) DESC
LIMIT 5)
GROUP BY d.name
ORDER BY frequency DESC
""")

Name  frequency
0         Barbecued Tofu Skewers          2
1                     Cheesecake          2
2            Quinoa Salmon Salad          2
3   Tomato Bruschetta Tortellini          2
4                 Classic Burger          1
5              French Onion Soup          1
6              Handcrafted Pizza          1
7                    House Salad          1
8               Mixed Berry Tart          1
9        Panko Stuffed Mushrooms          1
10          Pomegranate Iced Tea          1

Os clientes indicaram seus pratos favoritos em uma pesquisa. Quantas vezes cada prato do cardápio aparece nessa
coluna?

In [ ]:
execute_query("""
SELECT c.favoritedish, d.name, COUNT(*) AS frequency FROM customers c
INNER JOIN dishes d ON d.dishid = c.favoritedish
GROUP BY favoritedish
ORDER BY frequency DESC
""")

FavoriteDish                          Name  frequency
0              8                  Chef's Salad         13
1              5       Panko Stuffed Mushrooms          8
2             14         Fiesta Family Platter          7
3             15                  Creme Brulee          7
4              1         Parmesan Deviled Eggs          6
5              4            Mini Cheeseburgers          6
6             10                Classic Burger          6
7              2  Artichokes with Garlic Aioli          4
8              3             French Onion Soup          4
9             12             Handcrafted Pizza          4
10            13        Barbecued Tofu Skewers          4
11            18                     Apple Pie          4
12            20        Tropical Blue Smoothie          4
13            21          Pomegranate Iced Tea          4
14            22                    Cafe Latte          4
15             7                   House Salad          3
16            11  Tomato Bruschetta Tortellini          3
17            16                    Cheesecake          3
18             6                 Garden Buffet          2
19             9           Quinoa Salmon Salad          2
20            17        Chocolate Chip Brownie          1
21            19              Mixed Berry Tart          1

Vc poderia utilizar essa popularidade para recomendar um prato?

Recomendaria o Panko Stuffed Mushrooms. Está entre os 10 pratos mais baratos, entre os pratos que os clientes que gastam mais costumam pedir e é um prato frequentemente selecionado como favorito.


Qual evento fez mais sucesso?

In [ ]:
execute_query("""
SELECT *, COUNT(*) AS frequency FROM events 
GROUP BY name
ORDER BY frequency DESC""")

EventID                      Name  \
0       14  Eating Healthy at School   
1        6         Winter Wonderland   
2       15                 Fall Ball   
3        8             Summer's Here   
4        7         Swing into Spring   

                                         Description                 Date  \
0  Did someone say Durian? Get the school year st...  2019-10-06 09:00:00   
1  Join us to celebrate 2019 in a garden of organ...  2019-01-01 18:00:00   
2  Why should winter get all the fancy ballroom d...  2019-10-31 17:00:00   
3  Join us by the pool at the Landon Hotel San Fr...  2019-06-25 11:00:00   
4  Swing into Spring with your favorite springtim...  2019-04-01 12:00:00   

                      Location  frequency  
0             Teaching Kitchen          6  
1                 Landon Hotel          6  
2  Rick's Organic Pumpkin Farm          1  
3                 Rooftop Pool          1  
4              The Kale Grotto          1

Quais clientes não possuem pedidos?

In [ ]:
execute_query("""
SELECT c.customerid, c.firstname, c.lastname FROM customers c
LEFT JOIN orders o ON c.customerid = o.customerid
WHERE o.orderid IS NULL
""")

CustomerID FirstName   LastName
0            1     Maggi     Domney
1            3     Aleen      Fasey
2            4    Taylor    Jenkins
3            5    Imogen     Kabsch
4            6      Dunc      Winny
..         ...       ...        ...
87          96  Melantha  Scowcroft
88          97      Herb  McParland
89          98      Clem      Durdy
90          99      Kala   Simonian
91         100    Blythe     Leggan

[92 rows x 3 columns]

Indique 5 pratos que estejam sempre entre os favoritos e que não sejam tão caros:



1. Panko Stuffed Mushrooms
2. Parmesan Deviled Eggs
3. Pomegranate Iced Tea	
4. Apple Pie
5. Tropical Blue Smoothie



## Otimizando a venda de cervejas no Carnaval 2022

In [ ]:
import pandas as pd

In [ ]:
path = '/content/drive/MyDrive/Bootcamp_Data_Science/DBs/consumo_cerveja.csv'

In [ ]:
cerveja_df = pd.read_csv(path)

In [ ]:
cerveja_df

Data Temperatura Media (C) Temperatura Minima (C)  \
0    2015-01-01                  27,3                   23,9   
1    2015-01-02                 27,02                   24,5   
2    2015-01-03                 24,82                   22,4   
3    2015-01-04                 23,98                   21,5   
4    2015-01-05                 23,82                     21   
..          ...                   ...                    ...   
936         NaN                   NaN                    NaN   
937         NaN                   NaN                    NaN   
938         NaN                   NaN                    NaN   
939         NaN                   NaN                    NaN   
940         NaN                   NaN                    NaN   

    Temperatura Maxima (C) Precipitacao (mm)  Final de Semana  \
0                     32,5                 0              0.0   
1                     33,5                 0              0.0   
2                     29,9                 0              1.0   
3                     28,6               1,2              1.0   
4                     28,3                 0              0.0   
..                     ...               ...              ...   
936                    NaN               NaN              NaN   
937                    NaN               NaN              NaN   
938                    NaN               NaN              NaN   
939                    NaN               NaN              NaN   
940                    NaN               NaN              NaN   

     Consumo de cerveja (litros)  
0                         25.461  
1                         28.972  
2                         30.814  
3                         29.799  
4                         28.900  
..                           ...  
936                          NaN  
937                          NaN  
938                          NaN  
939                          NaN  
940                          NaN  

[941 rows x 7 columns]

In [ ]:
#rows that are null
cerveja_df[cerveja_df.isna().any(axis=1)]

Data Temperatura Media (C) Temperatura Minima (C) Temperatura Maxima (C)  \
365  NaN                   NaN                    NaN                    NaN   
366  NaN                   NaN                    NaN                    NaN   
367  NaN                   NaN                    NaN                    NaN   
368  NaN                   NaN                    NaN                    NaN   
369  NaN                   NaN                    NaN                    NaN   
..   ...                   ...                    ...                    ...   
936  NaN                   NaN                    NaN                    NaN   
937  NaN                   NaN                    NaN                    NaN   
938  NaN                   NaN                    NaN                    NaN   
939  NaN                   NaN                    NaN                    NaN   
940  NaN                   NaN                    NaN                    NaN   

    Precipitacao (mm)  Final de Semana  Consumo de cerveja (litros)  
365               NaN              NaN                          NaN  
366               NaN              NaN                          NaN  
367               NaN              NaN                          NaN  
368               NaN              NaN                          NaN  
369               NaN              NaN                          NaN  
..                ...              ...                          ...  
936               NaN              NaN                          NaN  
937               NaN              NaN                          NaN  
938               NaN              NaN                          NaN  
939               NaN              NaN                          NaN  
940               NaN              NaN                          NaN  

[576 rows x 7 columns]

In [ ]:
beer_df = cerveja_df.dropna(axis=0, how= "all")

In [ ]:
beer_df

Data Temperatura Media (C) Temperatura Minima (C)  \
0    2015-01-01                  27,3                   23,9   
1    2015-01-02                 27,02                   24,5   
2    2015-01-03                 24,82                   22,4   
3    2015-01-04                 23,98                   21,5   
4    2015-01-05                 23,82                     21   
..          ...                   ...                    ...   
360  2015-12-27                    24                   21,1   
361  2015-12-28                 22,64                   21,1   
362  2015-12-29                 21,68                   20,3   
363  2015-12-30                 21,38                   19,3   
364  2015-12-31                 24,76                   20,2   

    Temperatura Maxima (C) Precipitacao (mm)  Final de Semana  \
0                     32,5                 0              0.0   
1                     33,5                 0              0.0   
2                     29,9                 0              1.0   
3                     28,6               1,2              1.0   
4                     28,3                 0              0.0   
..                     ...               ...              ...   
360                   28,2              13,6              1.0   
361                   26,7                 0              0.0   
362                   24,1              10,3              0.0   
363                   22,4               6,3              0.0   
364                     29                 0              0.0   

     Consumo de cerveja (litros)  
0                         25.461  
1                         28.972  
2                         30.814  
3                         29.799  
4                         28.900  
..                           ...  
360                       32.307  
361                       26.095  
362                       22.309  
363                       20.467  
364                       22.446  

[365 rows x 7 columns]

In [ ]:
beer_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365 entries, 0 to 364
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Data                         365 non-null    object 
 1   Temperatura Media (C)        365 non-null    object 
 2   Temperatura Minima (C)       365 non-null    object 
 3   Temperatura Maxima (C)       365 non-null    object 
 4   Precipitacao (mm)            365 non-null    object 
 5   Final de Semana              365 non-null    float64
 6   Consumo de cerveja (litros)  365 non-null    float64
dtypes: float64(2), object(5)
memory usage: 22.8+ KB


In [ ]:
dias_de_chuva = beer_df[beer_df["Precipitacao (mm)"] != "0"]

In [ ]:
dias_de_chuva["Consumo de cerveja (litros)"].mean()

24.617768707483

In [ ]:
dias_de_sol = beer_df[beer_df["Precipitacao (mm)"] == "0"]

In [ ]:
dias_de_sol["Consumo de cerveja (litros)"].mean()

25.929756880733937

In [ ]:
fim_de_semana = beer_df[beer_df["Final de Semana"] > 0]

In [ ]:
fim_de_semana["Consumo de cerveja (litros)"].mean()

28.92272115384617

In [ ]:
dia_util = beer_df[beer_df["Final de Semana"] == 0]

In [ ]:
dia_util["Consumo de cerveja (litros)"].mean()

23.998222222222218

In [ ]:
fim_de_semana_com_sol = beer_df[(beer_df["Precipitacao (mm)"] == "0") & (beer_df["Final de Semana"] > 0)]

In [ ]:
fim_de_semana_com_sol["Consumo de cerveja (litros)"].mean()

29.62181967213115

In [ ]:
fim_de_semana_com_chuva = beer_df[(beer_df["Precipitacao (mm)"] != "0") & (beer_df["Final de Semana"] > 0)]

In [ ]:
fim_de_semana_com_chuva["Consumo de cerveja (litros)"].mean()

27.930976744186044